version: "3.9"
    
services:
  db:
    image: mysql:latest
    restart: always
    ports: 
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: message_api
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      TZ: Asia/Jakarta
    networks:
      - net

  app:
    build: ./
    image: message_api
    restart: always
    ports: 
      - "2000:2000"
    environment: 
      SQLALCHEMY_DATABASE_URI: mysql+mysqlconnector://user:user@172.17.0.1:3310/message_api

    networks:
      - net
    
networks:
  net:
    driver: bridge